export const PHYSICS_CONSTANTS = {
  BASE_MAX_SPEED: 70,
  ACCELERATION: 30,
  STEER_SPEED: 2.5,
  DRIFT_THRESHOLD: 0.7,
  DRIFT_GRIP_DRY: 0.95,
  DRIFT_GRIP_WET: 0.98,
  NORMAL_GRIP: 0.05,
  BOOST_MULTIPLIER: 1.6,
  BRAKE_DECELERATION: 50,
};

export const NITRO_CONSTANTS = {
  MAX_NITRO: 100,
  DEPLETION_RATE: 30,
  REGENERATION_RATE: 5,
};

export const DAY_NIGHT_CONSTANTS = {
  DAY_DURATION: 120, // seconds
};

export const SCORING_CONSTANTS = {
  COIN_VALUE: 10,
  FINISH_LINE_DISTANCE: 200,
};
